spring:
  profiles:
    active: local
  freemarker:
    cache: false
    template-loader-path: classpath:/templates
    suffix: .ftl
  security:
      user:
        name: user
        password: 1234

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health

jpa:
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      ddl-auto: update

logging:
  level:
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql: trace
---
# local
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ppp_board?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: '00000000'

pppboard:
  db-crypto-key: sfocubekftcdbsha2key

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: pppboard
    credentials:
        access-key: AKIAR76JUCXM2MDME3UG
        secret-key: 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